### PR TITLE
Add: v2 preload fonts to avoid CLS by fonts loading

### PR DESCRIPTION
**Pull request by Fasping**
This is a version 2 of PR #114 from @Felix-Icaza  🍻

-------------------------------

The rel="preconnect" link type tells the browser to establish a connection to the server that hosts the font resources as early as possible, which can improve the time it takes for the fonts to start loading.

The media attribute specifies that the fonts should only be loaded when the page is being printed, which can help reduce the amount of data that is downloaded when the page is initially loaded.

In the case of fonts, we can use both rel="preconnect" and rel="preload" to optimize their loading (its not the same). rel="preconnect" can help establish a connection to the server that hosts the fonts as early as possible, while rel="preload" can help start downloading the fonts as soon as possible.

### CODE REVIEW

**Comment by Felix-Icaza** [comment]
Thanks @Fasping!

**Comment by Felix-Icaza** [comment]
One observation @Fasping, I think that with the `media="print"` attribute the fonts will only be preloaded in print mode, you can correct me if I am wrong.

**Comment by Felix-Icaza** [comment]
You can add this shorthand for the `rel` attribute: `rel="preload preconnect"`.

**Comment by Fasping** [comment]
I modify the commit with your proposal  @Felix-Icaza 
I think you was right ! 
Gracias <3

**Pull request merged**
