### PR TITLE
fix error reading empty matches & team cards bug

### PR DESCRIPTION
**Pull request by felipetodev**
- [x] fix error reading empty pending matches in `NextMatchesTable`
- [x] fix unclosed div fixing `TeamsSelectorCards` bug

Fixes: https://github.com/midudev/kings-league-project/issues/277

### 1. NextMatchesTable
Captura de pantalla 2023-01-08 a la(s) 16 19 40

### 2. TeamsSelectorCards bug
image

image

### CODE REVIEW

**Comment by PChaparro** [comment]
Hi @felipetodev, What do you think about add something like the following code instead of the optional chaining to avoid render an empty header: 

```javascript
{
	firstDayWithPendingMatches && (
		<div class='relative overflow-x-auto shadow-md sm:rounded-lg'>
		</div>
	)
}
```

**Comment by felipetodev** [comment]
> Hi @felipetodev, What do you think about add something like the following code instead of the optional chaining to avoid render an empty header:
> 
> ```js
> {
> 	firstDayWithPendingMatches && (
> 		<div class='relative overflow-x-auto shadow-md sm:rounded-lg'>
>                 ...
> 		</div>
> 	)
> }
> ```

you right! thanks 4 the advice @PChaparro ✌️

**Comment by PChaparro** [comment]
@felipetodev Can you confirm if closing the non closed `<div>` tag fixes the #277 issue?

**Comment by felipetodev** [comment]
> @felipetodev Can you confirm if closing the non closed `<div>` tag fixes the #277 issue?

Yes, closing that div that section works correctly

**Comment by PChaparro** [comment]
> Yes, closing that div that section works correctly

Nice! Can you add the issue number on the pull request description? That will make the issue to close automatically when this pull request goes merged. 

You can add it like this: 

Fixes: # 277 

(Remove the space between the # and the number).

**Comment by felipetodev** [comment]
> > Yes, closing that div that section works correctly
> 
> Nice! Can you add the issue number on the pull request description? That will make the issue to close automatically when this pull request goes merged.
> 
> You can add it like this:
> 
> Fixes: # 277
> 
> (Remove the space between the # and the number).

Ready. Thank you! @PChaparro 🫰

**Pull request closed without merging**
