### PR TITLE
Add: upgrade test and improve

### PR DESCRIPTION
**Pull request by Fasping**
Hi everyone, 🍻

In this PR I have implemented some changes to the tests for the /schedule route to improve their clarity and accuracy. Specifically:

- The use of toHaveProperty has been replaced with toMatchObject to validate that an object has certain properties. This allows us to more accurately describe the properties we expect to find in the object, rather than simply checking that a specific property exists.
- The use of toHaveLength has been replaced with toBe to validate the length of an array. This allows us to directly compare the value of the array's length with the expected value, rather than checking that the array's length meets a specific condition.
- A test has been added to validate that the result of the /schedule request is correct in terms of the structure and properties of the objects in the schedule. This ensures that the schedule being returned is correct and that each of its elements has the expected properties.

I hope these changes are useful and improve the quality of the tests. 

**Thank you for reviewing!**

### CODE REVIEW

**Comment by PChaparro** [comment]
Thanks for the improvements, I'll consider them for the next tests :beers:

**Comment by Fasping** [comment]
@PChaparro but still failed test to PR.

If you can review and suggest solution can be lovely !

**Comment by PChaparro** [comment]
> If you can review and suggest solution can be lovely !

The problem isn't on the `/api/index.test.js`. Check the `/db/index.test.js`. Apparently Midu changed the url for all the images, you can check it [here](https://github.githistory.xyz/midudev/kings-league-project/blob/main/db/teams.json) :

**Comment by PChaparro** [comment]
@Fasping i didn't found similar cases of `toMatchObject` function being uses to check the type of an object's attributes. What do you think about this implementation: 

```javascript
it('Days should have their date and matches', async () => {
	const resp = await worker.fetch('/schedule')
	const days = await resp.json()
	
	const properties = [
		{ name: 'date', type: 'string' },
		{ name: 'matches', type: 'object' }
	]

	days.forEach((day) => {
		properties.forEach((property) => {
			const { name, type } = property
			expect(day).toHaveProperty(name)
			expect(day[name]).toBeTypeOf(type)
		})
	})
})
```

**Pull request closed without merging**
