### PR TITLE
one line return

### PR DESCRIPTION
**Pull request by JordiNodeJS**
Just a formated code, converting an arrow function with return in an implicit return for simple statements.

### CODE REVIEW

**Comment by Fasping** [comment]
Hey, thanks for your first commit! 🚀

I noticed that you might not be familiar with our style guidelines for commits. 
I recommend taking a look at the `CONTRIBUTING.md` file to see how we like to format our commit messages. 

This will help you follow the same style that we use, which will make it easier for everyone to understand the changes that are being made. 

Let me know if you have any questions about this!

https://midu.dev/buenas-practicas-escribir-commits-git/

**Review by Fasping — CHANGES_REQUESTED** [review]
It's generally a good idea to keep the return statement in this case, even though it is not strictly necessary. The return statement makes it explicit that you are returning a value from the function, which can make the code easier to read and understand.

In this case, the return statement also serves to exit the function early, which can be useful if you have additional code after the ctx.json() call that you do not want to execute.

Additionally, using the return statement can make it easier to spot mistakes or unintended behavior in your code. For example, if you forget to include the return statement and you have additional code after the ctx.json() call, the function will continue to execute that code, which could lead to unexpected results.

Overall, using the return statement can make your code more readable and easier to understand, and can help you avoid potential issues or bugs. I recommend keeping the return statement in this case.

**Comment by JordiNodeJS** [comment]
### Just a question:
For clarity or much simpler reading:
- 1ª case: `app.get('/leaderboard', (ctx) => ctx.json(leaderboard))`  OR
- 2ª case: `app.get('/leaderboard', ctx => ctx.json(leaderboard))`

If 2ª is the case: [omit parens when possible](https://prettier.io/docs/en/options.html#arrow-function-parentheses). Can we change *prettierrc.js* --> `arrowParens: "avoid"`? In this case all project wil be afected in the format.
What's your piece of advice, your recomendation in these cases?

**Comment by Fasping** [comment]
In general, it's a good practice to omit parentheses when possible to improve readability and make the code more concise. However, whether or not to use "avoid" for the arrowParens setting in prettierrc.js ultimately depends on your team's coding style guidelines and preferences ( in this case in @midudev). 

If you decide to use "avoid", it will affect the formatting of all the code in the project, so it's important to make sure that this is something that your team ( @midudev ) is comfortable with.

🍻

**Pull request merged**
