### PR TITLE
fix header background color

### PR DESCRIPTION
**Pull request by felixicaza**
This is related with the issue #248.

I'm proposing a new color for the background header, because it does not have good contrast with the team logos.

Current:

Screenshot_2023-01-08_08-48-39

(Edit: update proposals)

**Option 1**:

Screenshot_2023-01-08_12-10-59

**Option 2 (add black border - pending to commit)**:

Screenshot_2023-01-08_12-14-30

**Option 3 (add shadow - pending to commit)**:

Screenshot_2023-01-08_12-09-50

### CODE REVIEW

**Comment by 1fbr** [comment]
I assume the current one is like this to try to match the design of the logo.
Can you add a black outline to your proposal?  
I think it could combine the two proposals well.

**Comment by Felix-Icaza** [comment]
> I assume the current one is like that to try to match the design of the logo. Can you add a black outline to your proposal? I think it could combine the two proposals well.

Yes, I also like the style to match the logo design, but it doesn't have good contrast with some logos, so I just reversed the colors.

I don't understand about the black outline, can you provide a reference? So I could give it a try.

**Comment by 1fbr** [comment]
> Yes, I also like the style to match the logo design, but it doesn't have good contrast with some logos, so I just reversed the colors.
> I don't understand about the black outline, can you provide a reference? So I could give it a try.

Yes, I like the way you have inverted the colour. 
My suggestion is to add an extra black outline. So it would be, black - yellow - black - yellow like the logo.
The original has this black outline, notice when this line connects with the logo, it looks better in my opinion.

**Comment by Felix-Icaza** [comment]
> > Yes, I also like the style to match the logo design, but it doesn't have good contrast with some logos, so I just reversed the colors.
> > I don't understand about the black outline, can you provide a reference? So I could give it a try.
> 
> Yes, I like the way you have inverted the colour. My suggestion is to add an extra black outline. So it would be, black - yellow - black - yellow like the logo. The original has this black outline, notice when this line connects with the logo, it looks better in my opinion.

You mean something like this?

Screenshot_2023-01-08_11-43-51

**Comment by 1fbr** [comment]
@Felix-Icaza Yes, what do you think?

**Comment by Felix-Icaza** [comment]
> @Felix-Icaza Yes, what do you think?

It makes a lot of sense your suggestion. I just added a new suggestion where I add a shadow and attached fullscreen screenshots for better viewing, you can take a look at it.

I will draft the PR while we can decide.

**Comment by 1fbr** [comment]
> It makes a lot of sense your suggestion. I just added a new suggestion where I add a shadow and attached fullscreen screenshots for better viewing, you can take a look at it.
> 
> I will draft the PR while we can decide.

Both seem good to me, actually.
It would be good to have more opinions.

**Comment by Felix-Icaza** [comment]
Hi @midudev, what do you think?

**Pull request closed without merging**
